# Generated by Django 4.2 on 2024-03-06 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_adminreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='password',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Password must contain at least 8 characters, including at least one lowercase letter, one uppercase letter, one digit, and one special character.', regex='(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+{}\\[\\]:;<>,.?~\\\\/-]).{8,}')]),
        ),
    ]
