# Generated by Django 4.2 on 2024-03-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('InscClaimAmtReimbursed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DeductibleAmtPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PotentialFraud', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('race', models.CharField(max_length=50)),
                ('RenalDiseaseIndicator', models.CharField(max_length=1)),
                ('NoOfMonths_PartACov', models.IntegerField()),
                ('NoOfMonths_PartBCov', models.IntegerField()),
                ('ChronicCond_Alzheimer', models.BooleanField(default=False)),
                ('ChronicCond_Heartfailure', models.BooleanField(default=False)),
                ('ChronicCond_KidneyDisease', models.BooleanField(default=False)),
                ('ChronicCond_Cancer', models.BooleanField(default=False)),
                ('ChronicCond_ObstrPulmonary', models.BooleanField(default=False)),
                ('ChronicCond_Depression', models.BooleanField(default=False)),
                ('ChronicCond_Diabetes', models.BooleanField(default=False)),
                ('ChronicCond_IschemicHeart', models.BooleanField(default=False)),
                ('ChronicCond_Osteoporasis', models.BooleanField(default=False)),
                ('ChronicCond_rheumatoidarthritis', models.BooleanField(default=False)),
                ('ChronicCond_stroke', models.BooleanField(default=False)),
                ('IPAnnualReimbursementAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IPAnnualDeductibleAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OPAnnualReimbursementAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OPAnnualDeductibleAmt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
