# Generated by Django 4.2 on 2024-04-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provideno', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
    ]
