# Generated by Django 4.2 on 2024-04-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_remove_patient_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='email',
            new_name='BeneficiaryId',
        ),
        migrations.AddField(
            model_name='patient',
            name='provider',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='agemail',
            field=models.EmailField(max_length=40),
        ),
    ]
