# Generated by Django 4.2 on 2024-04-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0011_patient_agemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='agemail',
        ),
    ]
