# Generated by Django 4.2 on 2024-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0012_remove_patient_agemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='agemail',
            field=models.EmailField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
