# Generated by Django 4.2 on 2024-04-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0013_patient_agemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='RenalDiseaseIndicator',
            field=models.CharField(max_length=10),
        ),
    ]
