# Generated by Django 4.2 on 2024-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0016_alter_agent_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BeneficiaryId',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
