# Generated by Django 4.2 on 2024-04-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0017_alter_patient_beneficiaryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BeneficiaryId',
            field=models.CharField(max_length=40),
        ),
    ]
