# Generated by Django 4.2 on 2024-04-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0019_alter_patient_beneficiaryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Numberofdaysadmitted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
