# Generated by Django 5.0.4 on 2024-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0020_patient_numberofdaysadmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
