# Generated by Django 5.0.4 on 2024-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0021_reg_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='agent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
